### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by Izopi4a** [test-to-com/zep-to-php#1]
Hi,
can you give me a bit of help with these errors 

```

root@server1:/home/user/zep-to-php (master)$> chmod -R 777 .
root@server1:/home/user/zep-to-php (master)$> ./install
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/xx.h’: No such file or directory
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/lemon.c’: No such file or directory
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/lempar.c’: No such file or directory
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/parser.lemon’: No such file or directory
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/base.c’: No such file or directory
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/scanner.re’: No such file or directory
cp: cannot stat ‘/home/user/zep-to-php/externals/zephir/parser/scanner.h’: No such file or directory
gcc-4.8.real: error: lemon.c: No such file or directory
gcc-4.8.real: fatal error: no input files
compilation terminated.
re2c: error: cannot open scanner.re
ERROR: failed to produce parser

```

**Comment by Izopi4a** [comment]
oh i see, it should be installed 

```
git clone --recursive https://github.com/test-to-com/zep-to-php.git

```

but I cant find the php files after that ... where are they placed ? :D

**Comment by pjacferreira** [comment]
Hi

Probably the easiest solution for you is to specify the output directory. Something like:

zeptophp -o /tmp

This will be where the output files go.

If you don't specify an output directory, it calculates an output directory to use, so it should output your file, to the same directory as the input file/directory (i.e. if you have an input file like ~/test/input.zep, after running zeptophp, you should have an ~/test/input.php).

This is still a work in progress, so in the future, I hope things will be simpler.

Hope this help.

**Comment by Izopi4a** [comment]
great, excellent work :+1:

**Comment by pjacferreira** [comment]
Also, if you just want to see the translation of the ZEP, output to the console, please look in the .../zep-to-php/main.php file.

You should see something like:

```
$di->setShared('emitter', "\ZEPtoPHP\Emitters\File");
// $di->setShared('emitter', "\ZEPtoPHP\Emitters\Console");
```

If you comment out the line containing ...\Emitters\File, and uncomment the line ...\Emitters\Console, the output will just go to the console (nothing written to file).
